name: 'JIRA Autolinks Sync'
description: 'Sync JIRA projects with GitHub repository autolinks'
author: 'IlyaGulya'

inputs:
  action:
    description: 'Action to perform: sync (default) or list-categories'
    required: false
    default: 'sync'
  github-token:
    description: 'GitHub token for API access (required for sync action)'
    required: false
    default: ${{ github.token }}
  jira-url:
    description: 'JIRA instance URL'
    required: true
  jira-username:
    description: 'JIRA username'
    required: true
  jira-api-token:
    description: 'JIRA API token'
    required: true
  repository:
    description: 'Repository in format owner/repo (used for sync action)'
    required: false
    default: ${{ github.repository }}
  dry-run:
    description: 'Run in dry-run mode (plan only, no changes) (used for sync action)'
    required: false
    default: 'false'
  filter-project-category-ids:
    description: 'Filter JIRA projects by category ID (optional, comma-separated for multiple) (used for sync action)'
    required: false
  filter-project-type:
    description: 'Filter JIRA projects by type (optional, comma-separated: business, service_desk, software) (used for sync action)'
    required: false
  filter-project-query:
    description: 'Filter JIRA projects by literal string matching project key or name (case insensitive) (used for sync action)'
    required: false
  max-parallel-requests-github:
    description: 'Maximum number of parallel GitHub API requests (default: 5)'
    required: false
    default: '5'

outputs:
  projects-synced:
    description: 'Number of JIRA projects processed'
  autolinks-processed:
    description: 'Number of autolink operations performed (create/update/delete)'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'link'
  color: 'blue'
