name: 'JIRA Autolinks Sync'
description: 'Sync JIRA projects with GitHub repository autolinks'
author: 'IlyaGulya'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
    default: ${{ github.token }}
  jira-url:
    description: 'JIRA instance URL'
    required: true
  jira-username:
    description: 'JIRA username'
    required: true
  jira-api-token:
    description: 'JIRA API token'
    required: true
  repository:
    description: 'Repository in format owner/repo'
    required: false
    default: ${{ github.repository }}
  dry-run:
    description: 'Run in dry-run mode (plan only, no changes)'
    required: false
    default: 'false'

outputs:
  projects-synced:
    description: 'Number of JIRA projects processed'
  autolinks-processed:
    description: 'Number of autolink operations performed (create/update/delete)'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'link'
  color: 'blue'
